create database TesisGrover;

use TesisGrover;

CREATE TABLE Candidatos_Exoplanetas (
    kepid BIGINT PRIMARY KEY,
    kepoi_name VARCHAR(50),
    kepler_name VARCHAR(100),
    koi_disposition VARCHAR(50),
    koi_pdisposition VARCHAR(50),
    koi_score FLOAT,    
    koi_fpflag_nt BOOLEAN,
    koi_fpflag_ss BOOLEAN,
    koi_fpflag_co BOOLEAN,
    koi_fpflag_ec BOOLEAN,    
    koi_period FLOAT,
    koi_period_err1 FLOAT,
    koi_period_err2 FLOAT,    
    koi_time0bk FLOAT,
    koi_time0bk_err1 FLOAT,
    koi_time0bk_err2 FLOAT,    
    koi_impact FLOAT,
    koi_impact_err1 FLOAT,
    koi_impact_err2 FLOAT,    
    koi_duration FLOAT,
    koi_duration_err1 FLOAT,
    koi_duration_err2 FLOAT,    
    koi_depth FLOAT,
    koi_depth_err1 FLOAT,
    koi_depth_err2 FLOAT,    
    koi_prad FLOAT,
    koi_prad_err1 FLOAT,
    koi_prad_err2 FLOAT,    
    koi_teq FLOAT,
    koi_teq_err1 FLOAT,
    koi_teq_err2 FLOAT,    
    koi_insol FLOAT,
    koi_insol_err1 FLOAT,
    koi_insol_err2 FLOAT,    
    koi_model_snr FLOAT,    
    koi_tce_plnt_num INT,
    koi_tce_delivname VARCHAR(100),   
    koi_steff FLOAT,
    koi_steff_err1 FLOAT,
    koi_steff_err2 FLOAT,    
    koi_slogg FLOAT,
    koi_slogg_err1 FLOAT,
    koi_slogg_err2 FLOAT,    
    koi_srad FLOAT,
    koi_srad_err1 FLOAT,
    koi_srad_err2 FLOAT,    
    ra FLOAT,
    declination FLOAT,    
    koi_kepmag FLOAT
);
